# Generated by Django 5.0 on 2024-10-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopost',
            old_name='image1',
            new_name='image1',
        ),
    ]
